name: documentation

on: [push, pull_request]

jobs:
  indent:
    name: indent
    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ginggs/deal.ii-9.2.0-backports
        sudo apt-get update
        sudo apt-get install libdeal.ii-dev doxygen
        doxygen --version
    - name: indent
      run: |
        cmake .
